name: SSL Expiry Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run everyday at midnight
  workflow_dispatch:    # Allow manual triggering

jobs:
  check_ssl_expiry:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyopenssl

    - name: Run SSL Expiry Check
      run: |
        python .github/check_ssl_expiry.py
