name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Execute command on server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }} "echo Hello from Github actions"
